#!/usr/bin/env bash
# swarm_provision.sh — Fleet node provisioner (Termux · RunPod · local)
#
# Reads .env.fleet, detects host context, writes per-node env, boots miners.
#
# Usage:
#   cp .env.fleet.example .env.fleet   # first time; fill nodes 4–8
#   ./swarm_provision.sh 0             # Pixel 10a / Grass
#   ./swarm_provision.sh 1             # IoTeX Pebble node 1
#   ./swarm_provision.sh 7             # RunPod compute
#
# Sync to remote Termux / RunPod:
#   rsync -avz .env.fleet swarm_provision.sh phone:~/yieldswarm-agent-swarm-v2/
#   ssh phone 'cd ~/yieldswarm-agent-swarm-v2 && ./swarm_provision.sh 0'
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}"
FLEET_FILE="${FLEET_FILE:-${REPO_ROOT}/.env.fleet}"
NODE_INDEX="${1:-}"

log() { printf '[swarm-provision] %s\n' "$*" >&2; }

die() { log "ERROR: $*"; exit 1; }

# --- Load fleet matrix -------------------------------------------------------
[[ -f "${FLEET_FILE}" ]] || die ".env.fleet not found — run: cp .env.fleet.example .env.fleet"

set -a
# shellcheck disable=SC1090
source "${FLEET_FILE}"
set +a

[[ -n "${NODE_INDEX}" ]] || die "Usage: ./swarm_provision.sh [0-8]"

if ! [[ "${NODE_INDEX}" =~ ^[0-8]$ ]]; then
  die "Node index must be 0–8 (got: ${NODE_INDEX})"
fi

# Dynamic variable lookup (bash indirection)
role_var="NODE_${NODE_INDEX}_ROLE"
model_var="NODE_${NODE_INDEX}_MODEL"
serial_var="NODE_${NODE_INDEX}_SERIAL"
mac_var="NODE_${NODE_INDEX}_MAC"
platform_var="NODE_${NODE_INDEX}_PLATFORM"
sticker_var="NODE_${NODE_INDEX}_STICKER"
ssid_var="NODE_${NODE_INDEX}_SSID"
wallet_var="NODE_${NODE_INDEX}_WALLET"

TARGET_ROLE="${!role_var:-}"
TARGET_MODEL="${!model_var:-}"
TARGET_SERIAL="${!serial_var:-}"
TARGET_MAC="${!mac_var:-}"
TARGET_PLATFORM="${!platform_var:-linux}"
TARGET_STICKER="${!sticker_var:-}"
TARGET_SSID="${!ssid_var:-}"
TARGET_WALLET="${!wallet_var:-${FLEET_DEFAULT_WALLET:-}}"

[[ -n "${TARGET_MODEL}" && "${TARGET_MODEL}" != "CHANGEME" ]] || \
  die "Node ${NODE_INDEX} missing MODEL in .env.fleet (still CHANGEME?)"

# --- Detect execution context ------------------------------------------------
detect_context() {
  if [[ -n "${TERMUX_VERSION:-}" ]] || [[ -d /data/data/com.termux ]]; then
    echo "termux"
  elif [[ -n "${RUNPOD_POD_ID:-}" ]] || hostname 2>/dev/null | grep -qi runpod; then
    echo "runpod"
  elif [[ -n "${AZURE_INSTANCE_ID:-}" ]] || hostname 2>/dev/null | grep -qi vmss; then
    echo "azure"
  else
    echo "local"
  fi
}

CONTEXT="$(detect_context)"
log "context=${CONTEXT} node=${NODE_INDEX} role=${TARGET_ROLE} model=${TARGET_MODEL}"

# --- Workspace ---------------------------------------------------------------
export YIELDSWARM_REPO="${YIELDSWARM_REPO:-$HOME/yieldswarm-agent-swarm-v2}"
if [[ ! -d "${YIELDSWARM_REPO}/mining" ]]; then
  die "repo missing at ${YIELDSWARM_REPO} — clone first (use ~/ not \\~)"
fi
cd "${YIELDSWARM_REPO}"

# Operator overlays
for f in "${HOME}/.config/yieldswarm/nexus.env" deploy/akash.env deploy/config.env; do
  [[ -f "${f}" ]] || continue
  set -a
  # shellcheck disable=SC1090
  source "${f}"
  set +a
  log "loaded ${f}"
done

# --- Strip stale screen/tmux sessions ----------------------------------------
if command -v screen >/dev/null 2>&1; then
  screen -ls 2>/dev/null | grep -E 'yieldswarm|helix|mining' | awk -F. '{print $1}' | while read -r sid; do
    [[ -n "${sid}" ]] && screen -S "${sid}" -X quit 2>/dev/null || true
  done
  log "cleared stale screen sessions"
fi

# --- Write per-node deploy artifact ------------------------------------------
NODE_ENV_DIR="${REPO_ROOT}/deploy/fleet"
mkdir -p "${NODE_ENV_DIR}" "${REPO_ROOT}/.run/fleet"
NODE_ENV_FILE="${NODE_ENV_DIR}/node-${NODE_INDEX}.env"

cat >"${NODE_ENV_FILE}" <<EOF
# Auto-generated by swarm_provision.sh — node ${NODE_INDEX}
FLEET_NODE_INDEX=${NODE_INDEX}
FLEET_NODE_ROLE=${TARGET_ROLE}
FLEET_NODE_MODEL=${TARGET_MODEL}
FLEET_NODE_SERIAL=${TARGET_SERIAL}
FLEET_NODE_MAC=${TARGET_MAC}
FLEET_NODE_PLATFORM=${TARGET_PLATFORM}
IOT_NETWORK_ID=${FLEET_NETWORK_ID:-${FLEET_ID:-FWA_37KN9S-IoT}}
EOF

export PYTHONPATH="${REPO_ROOT}${PYTHONPATH:+:${PYTHONPATH}}"

# Export mining / IoT JSON env from fleet row into this shell
eval "$(python3 "${REPO_ROOT}/scripts/fleet/fleet_export.py" --node "${NODE_INDEX}" --fleet "${FLEET_FILE}")"

{
  echo "FLEET_NODE_ROLE=${TARGET_ROLE}"
  [[ -n "${GRASS_NODE_KEYS:-}" ]] && echo "GRASS_NODE_KEYS=${GRASS_NODE_KEYS}"
  [[ -n "${DEPIN_HELIUM_HOTSPOT_KEYS:-}" ]] && echo "DEPIN_HELIUM_HOTSPOT_KEYS=${DEPIN_HELIUM_HOTSPOT_KEYS}"
  [[ -n "${FLEET_NODE_WALLET:-}" ]] && echo "FLEET_NODE_WALLET=${FLEET_NODE_WALLET}"
} >>"${NODE_ENV_FILE}"

# shellcheck disable=SC1090
source "${NODE_ENV_FILE}"

log "wrote ${NODE_ENV_FILE}"

# --- Context-specific boot ---------------------------------------------------
case "${CONTEXT}" in
  termux)
    command -v termux-wake-lock >/dev/null 2>&1 && termux-wake-lock || true
    ;;
  runpod)
    export MINING_DRY_RUN="${MINING_DRY_RUN:-0}"
    ;;
esac

provision_grass() {
  log "booting Grass lineup (platform=${TARGET_PLATFORM})..."
  python3 -m mining config
  if [[ "${CONTEXT}" == "termux" && -x scripts/mining/start-termux.sh ]]; then
    ./scripts/mining/start-termux.sh
  else
    python3 -m mining start --miner grass
  fi
}

provision_helium() {
  log "booting Helium hotspot payload..."
  python3 -m mining config
  ./scripts/mining/deploy-helium-hotspot.sh --config "${REPO_ROOT}/.run/mining/helium-config.json"
  python3 -m mining start --miner helium
}

provision_iotex() {
  log "registering IoTeX Pebble with IoT Hub..."
  if [[ -x scripts/iot-hub/register-devices.sh ]]; then
    IOT_DEVICE_ID="pebble-${NODE_INDEX}" \
    IOT_DEVICE_SERIAL="${TARGET_SERIAL}" \
    IOT_DEVICE_MAC="${TARGET_MAC}" \
      ./scripts/iot-hub/register-devices.sh || log "WARN: iot register failed"
  fi
  python3 -m mining config 2>/dev/null || true
}

provision_compute() {
  log "booting compute node (Bittensor / orchestrator)..."
  if [[ -x scripts/start-mining.sh ]]; then
    MINING_DRY_RUN="${MINING_DRY_RUN:-1}" ./scripts/start-mining.sh || true
  fi
  python3 -m mining start --miner bittensor 2>/dev/null || python3 -m mining start
}

case "${TARGET_ROLE}" in
  grass|phone) provision_grass ;;
  helium) provision_helium ;;
  iotex) provision_iotex ;;
  compute) provision_compute ;;
  *)
    die "unknown NODE_${NODE_INDEX}_ROLE=${TARGET_ROLE}"
    ;;
esac

# --- Optional detached session -----------------------------------------------
if command -v screen >/dev/null 2>&1 && [[ "${SWARM_PROVISION_SCREEN:-1}" == "1" ]]; then
  SESSION="yieldswarm-node-${NODE_INDEX}"
  screen -dmS "${SESSION}" bash -lc "cd '${REPO_ROOT}' && tail -f .run/mining/orchestrator.log 2>/dev/null || sleep infinity"
  log "screen session: ${SESSION} (attach: screen -r ${SESSION})"
fi

log "provision complete — node ${NODE_INDEX} (${TARGET_MODEL})"
python3 -m mining status 2>/dev/null || true
