#!/usr/bin/env python3
"""Generate config/alchemy/christophers-first-app.json from Alchemy host slugs."""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "config" / "alchemy" / "christophers-first-app.json"

# Christopher's First App — Alchemy dashboard network hosts (no API key in repo)
NETWORKS: list[dict] = [
    {"id": "solana-mainnet", "name": "Solana Mainnet", "host": "solana-mainnet.g.alchemy.com", "family": "solana"},
    {"id": "solana-devnet", "name": "Solana Devnet", "host": "solana-devnet.g.alchemy.com", "family": "solana"},
    {"id": "worldchain-mainnet", "name": "World Chain Mainnet", "host": "worldchain-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "worldchain-sepolia", "name": "World Chain Sepolia", "host": "worldchain-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "shape-mainnet", "name": "Shape Mainnet", "host": "shape-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "shape-sepolia", "name": "Shape Sepolia", "host": "shape-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "ethereum-mainnet", "name": "Ethereum Mainnet", "host": "eth-mainnet.g.alchemy.com", "family": "evm", "chain_id": 1},
    {"id": "ethereum-sepolia", "name": "Ethereum Sepolia", "host": "eth-sepolia.g.alchemy.com", "family": "evm", "chain_id": 11155111},
    {"id": "ethereum-hoodi", "name": "Ethereum Hoodi", "host": "eth-hoodi.g.alchemy.com", "family": "evm"},
    {"id": "ethereum-mainnet-beacon", "name": "Ethereum Mainnet Beacon", "host": "eth-mainnetbeacon.g.alchemy.com", "family": "beacon"},
    {"id": "ethereum-sepolia-beacon", "name": "Ethereum Sepolia Beacon", "host": "eth-sepoliabeacon.g.alchemy.com", "family": "beacon"},
    {"id": "ethereum-hoodi-beacon", "name": "Ethereum Hoodi Beacon", "host": "eth-hoodibeacon.g.alchemy.com", "family": "beacon"},
    {"id": "zksync-mainnet", "name": "ZKsync Mainnet", "host": "zksync-mainnet.g.alchemy.com", "family": "evm", "chain_id": 324},
    {"id": "zksync-sepolia", "name": "ZKsync Sepolia", "host": "zksync-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "op-mainnet", "name": "OP Mainnet", "host": "opt-mainnet.g.alchemy.com", "family": "evm", "chain_id": 10},
    {"id": "op-sepolia", "name": "OP Sepolia", "host": "opt-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "polygon-mainnet", "name": "Polygon Mainnet", "host": "polygon-mainnet.g.alchemy.com", "family": "evm", "chain_id": 137},
    {"id": "polygon-amoy", "name": "Polygon Amoy", "host": "polygon-amoy.g.alchemy.com", "family": "evm"},
    {"id": "arbitrum-mainnet", "name": "Arbitrum Mainnet", "host": "arb-mainnet.g.alchemy.com", "family": "evm", "chain_id": 42161},
    {"id": "arbitrum-sepolia", "name": "Arbitrum Sepolia", "host": "arb-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "starknet-mainnet", "name": "Starknet Mainnet", "host": "starknet-mainnet.g.alchemy.com", "family": "starknet", "url_pattern": "starknet_v0_10"},
    {"id": "starknet-sepolia", "name": "Starknet Sepolia", "host": "starknet-sepolia.g.alchemy.com", "family": "starknet", "url_pattern": "starknet_v0_10"},
    {"id": "astar-mainnet", "name": "Astar Mainnet", "host": "astar-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "polygonzkevm-mainnet", "name": "Polygon zkEVM Mainnet", "host": "polygonzkevm-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "polygonzkevm-cardona", "name": "Polygon zkEVM Cardona", "host": "polygonzkevm-cardona.g.alchemy.com", "family": "evm"},
    {"id": "zetachain-mainnet", "name": "ZetaChain Mainnet", "host": "zetachain-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "zetachain-testnet", "name": "ZetaChain Testnet", "host": "zetachain-testnet.g.alchemy.com", "family": "evm"},
    {"id": "mantle-mainnet", "name": "Mantle Mainnet", "host": "mantle-mainnet.g.alchemy.com", "family": "evm", "chain_id": 5000},
    {"id": "mantle-sepolia", "name": "Mantle Sepolia", "host": "mantle-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "berachain-mainnet", "name": "Berachain Mainnet", "host": "berachain-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "berachain-bepolia", "name": "Berachain Bepolia", "host": "berachain-bepolia.g.alchemy.com", "family": "evm"},
    {"id": "linea-mainnet", "name": "Linea Mainnet", "host": "linea-mainnet.g.alchemy.com", "family": "evm", "chain_id": 59144},
    {"id": "linea-sepolia", "name": "Linea Sepolia", "host": "linea-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "zora-mainnet", "name": "Zora Mainnet", "host": "zora-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "zora-sepolia", "name": "Zora Sepolia", "host": "zora-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "robinhood-testnet", "name": "Robinhood Chain Testnet", "host": "robinhood-testnet.g.alchemy.com", "family": "evm"},
    {"id": "ronin-mainnet", "name": "Ronin Mainnet", "host": "ronin-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "ronin-saigon", "name": "Ronin Saigon", "host": "ronin-saigon.g.alchemy.com", "family": "evm"},
    {"id": "plasma-mainnet", "name": "Plasma Mainnet", "host": "plasma-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "plasma-testnet", "name": "Plasma Testnet", "host": "plasma-testnet.g.alchemy.com", "family": "evm"},
    {"id": "mythos-mainnet", "name": "Mythos Mainnet", "host": "mythos-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "settlus-mainnet", "name": "Settlus Mainnet", "host": "settlus-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "settlus-sepolia", "name": "Settlus Sepolia", "host": "settlus-septestnet.g.alchemy.com", "family": "evm"},
    {"id": "bob-mainnet", "name": "BOB Mainnet", "host": "bob-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "bob-sepolia", "name": "BOB Sepolia", "host": "bob-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "rootstock-mainnet", "name": "Rootstock Mainnet", "host": "rootstock-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "rootstock-testnet", "name": "Rootstock Testnet", "host": "rootstock-testnet.g.alchemy.com", "family": "evm"},
    {"id": "megaeth-mainnet", "name": "MegaETH Mainnet", "host": "megaeth-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "megaeth-testnet", "name": "MegaETH Testnet", "host": "megaeth-testnet.g.alchemy.com", "family": "evm"},
    {"id": "katana-bokuto", "name": "Katana Bokuto", "host": "katana-bokuto.g.alchemy.com", "family": "evm"},
    {"id": "katana-mainnet", "name": "Katana Mainnet", "host": "katana-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "dogecoin-mainnet", "name": "Dogecoin Mainnet", "host": "dogecoin-mainnet.g.alchemy.com", "family": "utxo"},
    {"id": "bitcoincash-mainnet", "name": "Bitcoin Cash Mainnet", "host": "bitcoincash-mainnet.g.alchemy.com", "family": "utxo"},
    {"id": "bitcoincash-testnet", "name": "Bitcoin Cash Testnet", "host": "bitcoincash-testnet.g.alchemy.com", "family": "utxo"},
    {"id": "citrea-testnet", "name": "Citrea Testnet", "host": "citrea-testnet.g.alchemy.com", "family": "evm"},
    {"id": "citrea-mainnet", "name": "Citrea Mainnet", "host": "citrea-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "gensyn-testnet", "name": "Gensyn Testnet", "host": "gensyn-testnet.g.alchemy.com", "family": "evm"},
    {"id": "gensyn-mainnet", "name": "Gensyn Mainnet", "host": "gensyn-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "arc-testnet", "name": "Arc Testnet", "host": "arc-testnet.g.alchemy.com", "family": "evm"},
    {"id": "clankermon-mainnet", "name": "Clankermon Mainnet", "host": "clankermon-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "story-mainnet", "name": "Story Mainnet", "host": "story-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "story-aeneid", "name": "Story Aeneid", "host": "story-aeneid.g.alchemy.com", "family": "evm"},
    {"id": "humanity-mainnet", "name": "Humanity Mainnet", "host": "humanity-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "humanity-testnet", "name": "Humanity Testnet", "host": "humanity-testnet.g.alchemy.com", "family": "evm"},
    {"id": "risa-testnet", "name": "Risa Testnet", "host": "risa-testnet.g.alchemy.com", "family": "evm"},
    {"id": "base-mainnet", "name": "Base Mainnet", "host": "base-mainnet.g.alchemy.com", "family": "evm", "chain_id": 8453},
    {"id": "base-sepolia", "name": "Base Sepolia", "host": "base-sepolia.g.alchemy.com", "family": "evm", "chain_id": 84532},
    {"id": "tempo-mainnet", "name": "Tempo Mainnet", "host": "tempo-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "tempo-moderato", "name": "Tempo Moderato", "host": "tempo-moderato.g.alchemy.com", "family": "evm"},
    {"id": "hyperliquid-mainnet", "name": "Hyperliquid Mainnet", "host": "hyperliquid-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "hyperliquid-testnet", "name": "Hyperliquid Testnet", "host": "hyperliquid-testnet.g.alchemy.com", "family": "evm"},
    {"id": "galactica-mainnet", "name": "Galactica Mainnet", "host": "galactica-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "galactica-cassiopeia", "name": "Galactica Cassiopeia", "host": "galactica-cassiopeia.g.alchemy.com", "family": "evm"},
    {"id": "lens-mainnet", "name": "Lens Mainnet", "host": "lens-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "lens-sepolia", "name": "Lens Sepolia", "host": "lens-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "worldmobilechain-mainnet", "name": "World Mobile Chain Mainnet", "host": "worldmobilechain-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "frax-mainnet", "name": "Frax Mainnet", "host": "frax-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "frax-sepolia", "name": "Frax Sepolia", "host": "frax-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "ink-mainnet", "name": "Ink Mainnet", "host": "ink-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "ink-sepolia", "name": "Ink Sepolia", "host": "ink-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "avalanche-mainnet", "name": "Avalanche Mainnet", "host": "avax-mainnet.g.alchemy.com", "family": "evm", "chain_id": 43114},
    {"id": "avalanche-fuji", "name": "Avalanche Fuji", "host": "avax-fuji.g.alchemy.com", "family": "evm"},
    {"id": "botanix-mainnet", "name": "Botanix Mainnet", "host": "botanix-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "botanix-testnet", "name": "Botanix Testnet", "host": "botanix-testnet.g.alchemy.com", "family": "evm"},
    {"id": "gnosis-mainnet", "name": "Gnosis Mainnet", "host": "gnosis-mainnet.g.alchemy.com", "family": "evm", "chain_id": 100},
    {"id": "gnosis-chiado", "name": "Gnosis Chiado", "host": "gnosis-chiado.g.alchemy.com", "family": "evm"},
    {"id": "celestiabridge-mainnet", "name": "CelestiaBridge Mainnet", "host": "celestiabridge-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "celestiabridge-mocha", "name": "CelestiaBridge Mocha", "host": "celestiabridge-mocha.g.alchemy.com", "family": "evm"},
    {"id": "bnb-mainnet", "name": "BNB Smart Chain Mainnet", "host": "bnb-mainnet.g.alchemy.com", "family": "evm", "chain_id": 56},
    {"id": "bnb-testnet", "name": "BNB Smart Chain Testnet", "host": "bnb-testnet.g.alchemy.com", "family": "evm"},
    {"id": "boba-mainnet", "name": "Boba Mainnet", "host": "boba-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "boba-sepolia", "name": "Boba Sepolia", "host": "boba-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "xlayer-testnet", "name": "X Layer Testnet", "host": "xlayer-testnet.g.alchemy.com", "family": "evm"},
    {"id": "xlayer-mainnet", "name": "X Layer Mainnet", "host": "xlayer-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "sui-mainnet", "name": "Sui Mainnet", "host": "sui-mainnet.g.alchemy.com", "family": "sui"},
    {"id": "sui-testnet", "name": "Sui Testnet", "host": "sui-testnet.g.alchemy.com", "family": "sui"},
    {"id": "kaia-testnet", "name": "Kaia Testnet", "host": "kaia-testnet.g.alchemy.com", "family": "evm"},
    {"id": "kaia-mainnet", "name": "Kaia Mainnet", "host": "kaia-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "stellar-mainnet", "name": "Stellar Mainnet", "host": "stellar-mainnet.g.alchemy.com", "family": "stellar"},
    {"id": "stellar-testnet", "name": "Stellar Testnet", "host": "stellar-testnet.g.alchemy.com", "family": "stellar"},
    {"id": "unichain-mainnet", "name": "Unichain Mainnet", "host": "unichain-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "unichain-sepolia", "name": "Unichain Sepolia", "host": "unichain-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "syndicate-mainnet", "name": "Syndicate Mainnet", "host": "synd-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "superseed-mainnet", "name": "Superseed Mainnet", "host": "superseed-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "superseed-sepolia", "name": "Superseed Sepolia", "host": "superseed-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "rise-testnet", "name": "Rise Testnet", "host": "rise-testnet.g.alchemy.com", "family": "evm"},
    {"id": "rise-mainnet", "name": "Rise Mainnet", "host": "rise-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "monad-testnet", "name": "Monad Testnet", "host": "monad-testnet.g.alchemy.com", "family": "evm"},
    {"id": "monad-mainnet", "name": "Monad Mainnet", "host": "monad-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "flow-mainnet", "name": "Flow EVM Mainnet", "host": "flow-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "flow-testnet", "name": "Flow EVM Testnet", "host": "flow-testnet.g.alchemy.com", "family": "evm"},
    {"id": "blast-mainnet", "name": "Blast Mainnet", "host": "blast-mainnet.g.alchemy.com", "family": "evm", "chain_id": 81457},
    {"id": "blast-sepolia", "name": "Blast Sepolia", "host": "blast-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "worldmobile-testnet", "name": "WorldMobile Testnet", "host": "worldmobile-testnet.g.alchemy.com", "family": "evm"},
    {"id": "injective-mainnet", "name": "Injective Mainnet", "host": "injective-mainnet.g.alchemy.com", "family": "cosmos"},
    {"id": "injective-testnet", "name": "Injective Testnet", "host": "injective-testnet.g.alchemy.com", "family": "cosmos"},
    {"id": "tron-mainnet", "name": "Tron Mainnet", "host": "tron-mainnet.g.alchemy.com", "family": "tron"},
    {"id": "tron-testnet", "name": "Tron Testnet", "host": "tron-testnet.g.alchemy.com", "family": "tron"},
    {"id": "jovay-mainnet", "name": "Jovay Mainnet", "host": "jovay-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "jovay-testnet", "name": "Jovay Testnet", "host": "jovay-testnet.g.alchemy.com", "family": "evm"},
    {"id": "degen-mainnet", "name": "Degen Mainnet", "host": "degen-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "bitcoin-mainnet", "name": "Bitcoin Mainnet", "host": "bitcoin-mainnet.g.alchemy.com", "family": "utxo"},
    {"id": "bitcoin-testnet", "name": "Bitcoin Testnet", "host": "bitcoin-testnet.g.alchemy.com", "family": "utxo"},
    {"id": "bitcoin-signet", "name": "Bitcoin Signet", "host": "bitcoin-signet.g.alchemy.com", "family": "utxo"},
    {"id": "bitcoin-testnet4", "name": "Bitcoin Testnet4", "host": "bitcoin-testnet4.g.alchemy.com", "family": "utxo"},
    {"id": "pharos-mainnet", "name": "Pharos Mainnet", "host": "pharos-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "pharos-atlantic", "name": "Pharos Atlantic", "host": "pharos-atlantic.g.alchemy.com", "family": "evm"},
    {"id": "mode-mainnet", "name": "Mode Mainnet", "host": "mode-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "mode-sepolia", "name": "Mode Sepolia", "host": "mode-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "edge-mainnet", "name": "Edge Mainnet", "host": "edge-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "edge-testnet", "name": "Edge Testnet", "host": "edge-testnet.g.alchemy.com", "family": "evm"},
    {"id": "litecoin-mainnet", "name": "Litecoin Mainnet", "host": "litecoin-mainnet.g.alchemy.com", "family": "utxo"},
    {"id": "litecoin-testnet", "name": "Litecoin Testnet", "host": "litecoin-testnet.g.alchemy.com", "family": "utxo"},
    {"id": "moonbeam-mainnet", "name": "Moonbeam Mainnet", "host": "moonbeam-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "apechain-mainnet", "name": "ApeChain Mainnet", "host": "apechain-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "apechain-curtis", "name": "ApeChain Curtis", "host": "apechain-curtis.g.alchemy.com", "family": "evm"},
    {"id": "celo-mainnet", "name": "Celo Mainnet", "host": "celo-mainnet.g.alchemy.com", "family": "evm", "chain_id": 42220},
    {"id": "celo-sepolia", "name": "Celo Sepolia", "host": "celo-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "aptos-mainnet", "name": "Aptos Mainnet", "host": "aptos-mainnet.g.alchemy.com", "family": "aptos"},
    {"id": "aptos-testnet", "name": "Aptos Testnet", "host": "aptos-testnet.g.alchemy.com", "family": "aptos"},
    {"id": "anime-mainnet", "name": "Anime Mainnet", "host": "anime-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "anime-sepolia", "name": "Anime Sepolia", "host": "anime-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "metis-mainnet", "name": "Metis Mainnet", "host": "metis-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "sonic-mainnet", "name": "Sonic Mainnet", "host": "sonic-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "sonic-testnet", "name": "Sonic Testnet", "host": "sonic-testnet.g.alchemy.com", "family": "evm"},
    {"id": "sei-mainnet", "name": "Sei Mainnet", "host": "sei-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "sei-testnet", "name": "Sei Testnet", "host": "sei-testnet.g.alchemy.com", "family": "evm"},
    {"id": "cronos-mainnet", "name": "Cronos Mainnet", "host": "cronos-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "cronos-testnet", "name": "Cronos Testnet", "host": "cronos-testnet.g.alchemy.com", "family": "evm"},
    {"id": "xmtp-ropsten", "name": "XMTP Ropsten", "host": "xmtp-ropsten.g.alchemy.com", "family": "evm"},
    {"id": "adi-testnet", "name": "ADI Testnet AB", "host": "adi-testnet.g.alchemy.com", "family": "evm"},
    {"id": "adi-mainnet", "name": "ADI Mainnet", "host": "adi-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "scroll-mainnet", "name": "Scroll Mainnet", "host": "scroll-mainnet.g.alchemy.com", "family": "evm", "chain_id": 534352},
    {"id": "scroll-sepolia", "name": "Scroll Sepolia", "host": "scroll-sepolia.g.alchemy.com", "family": "evm"},
    {"id": "opbnb-mainnet", "name": "opBNB Mainnet", "host": "opbnb-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "opbnb-testnet", "name": "opBNB Testnet", "host": "opbnb-testnet.g.alchemy.com", "family": "evm"},
    {"id": "abstract-mainnet", "name": "Abstract Mainnet", "host": "abstract-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "abstract-testnet", "name": "Abstract Testnet", "host": "abstract-testnet.g.alchemy.com", "family": "evm"},
    {"id": "soneium-mainnet", "name": "Soneium Mainnet", "host": "soneium-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "soneium-minato", "name": "Soneium Minato", "host": "soneium-minato.g.alchemy.com", "family": "evm"},
    {"id": "crossfi-testnet", "name": "CrossFi Testnet", "host": "crossfi-testnet.g.alchemy.com", "family": "evm"},
    {"id": "crossfi-mainnet", "name": "CrossFi Mainnet", "host": "crossfi-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "stable-mainnet", "name": "Stable Mainnet", "host": "stable-mainnet.g.alchemy.com", "family": "evm"},
    {"id": "stable-testnet", "name": "Stable Testnet", "host": "stable-testnet.g.alchemy.com", "family": "evm"},
]

def main() -> None:
    manifest = {
        "version": 1,
        "app": "Christopher's First App",
        "api_key_env": "ALCHEMY_API_KEY",
        "url_template_v2": "https://{host}/v2/{api_key}",
        "url_template_starknet_v0_10": "https://{host}/starknet/version/rpc/v0_10/{api_key}",
        "networks": {},
    }
    for row in NETWORKS:
        nid = row.pop("id")
        row["enabled"] = True
        manifest["networks"][nid] = row
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(manifest['networks'])} networks)")


if __name__ == "__main__":
    main()
