#!/usr/bin/env bash
# =============================================================================
# STEP 4 — Update the frontend with the real worker URLs.
#
#   deploy/scripts/update-frontend-urls.sh [url1 url2 ...]
#
# Collects live worker URLs from (in priority order):
#   1. CLI args
#   2. $WORKER_URLS (deploy/config.env)
#   3. The Akash lease            (.run/akash-lease.env -> AKASH_WORKER_URLS)
#   4. The Terraform fallback     (deploy/terraform/fallback-url.txt)
# then writes a runtime config consumed by the dashboard (FRONTEND_CONFIG_OUT,
# default dashboard/config.js) and optionally triggers a Vercel redeploy.
# =============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_config

collect_urls() {
  local -a urls=()
  # 1. args
  if [[ $# -gt 0 ]]; then urls+=("$@"); fi
  # 2. env
  if [[ -n "${WORKER_URLS}" ]]; then IFS=',' read -ra e <<< "$WORKER_URLS"; urls+=("${e[@]}"); fi
  # 3. akash lease
  local lease="${REPO_ROOT}/${RUN_DIR}/akash-lease.env"
  if [[ -f "$lease" ]]; then
    # shellcheck disable=SC1090
    source "$lease"
    if [[ -n "${AKASH_WORKER_URLS:-}" ]]; then IFS=',' read -ra a <<< "$AKASH_WORKER_URLS"; urls+=("${a[@]}"); fi
  fi
  # 4. terraform fallback
  local fb="${REPO_ROOT}/${TF_DIR}/fallback-url.txt"
  if [[ -f "$fb" ]]; then
    local u; u="$(tr -d '[:space:]' < "$fb")"
    [[ -n "$u" ]] && urls+=("${u%/healthz}")
  fi

  # Normalize: strip /healthz, strip trailing slash, dedupe, drop empties.
  local -A seen=(); local out=() x
  for x in "${urls[@]}"; do
    x="${x%/healthz}"; x="${x%/}"
    [[ -z "$x" ]] && continue
    if [[ -z "${seen[$x]:-}" ]]; then seen[$x]=1; out+=("$x"); fi
  done
  printf '%s\n' "${out[@]}"
}

write_config() {
  local out_file="${REPO_ROOT}/${FRONTEND_CONFIG_OUT}"
  mkdir -p "$(dirname "$out_file")"
  IMAGE_TAG="${IMAGE_TAG}" GENERATED_AT="$(date -u +%FT%TZ)" \
    python3 - "$out_file" "$@" <<'PY'
import json, os, sys
out_file = sys.argv[1]
urls = [u.strip() for u in sys.argv[2:] if u.strip()]
cfg = {
    "buildTag": os.environ.get("IMAGE_TAG", "unconfigured"),
    "generatedAt": os.environ.get("GENERATED_AT"),
    "workerUrls": urls,
    "primaryWorker": urls[0] if urls else None,
}
with open(out_file, "w") as f:
    f.write("// AUTO-GENERATED by deploy/scripts/update-frontend-urls.sh — do not edit.\n")
    f.write(f"// Generated: {cfg['generatedAt']}  |  build: {cfg['buildTag']}\n")
    f.write("window.YIELDSWARM_CONFIG = " + json.dumps(cfg, indent=2) + ";\n")
PY
  ok "wrote ${FRONTEND_CONFIG_OUT}"
}

maybe_redeploy_vercel() {
  if [[ -n "${VERCEL_DEPLOY_HOOK:-}" ]]; then
    step "Triggering Vercel redeploy"
    curl -fsS -X POST "${VERCEL_DEPLOY_HOOK}" >/dev/null && ok "Vercel redeploy triggered" \
      || warn "Vercel redeploy hook failed"
  fi
}

main() {
  step "STEP 4 — Update frontend with real worker URLs"
  require python3
  local urls; mapfile -t urls < <(collect_urls "$@")
  if [[ ${#urls[@]} -eq 0 ]]; then
    warn "no worker URLs found — writing empty config (set WORKER_URLS or run create-lease.sh first)"
  else
    step "Resolved ${#urls[@]} worker URL(s):"
    printf '   %s\n' "${urls[@]}"
  fi
  write_config "${urls[@]}"
  maybe_redeploy_vercel
  ok "STEP 4 complete"
}

main "$@"
