# TON mini game + Kairo driver layer
TONCENTER_API_KEY=${TONCENTER_API_KEY}
TON_MINI_APP_URL=${TON_MINI_APP_URL}
KAIRO_API_URL=${KAIRO_API_URL:-http://127.0.0.1:8100}
KAIRO_PUBLIC_API_BASE=${KAIRO_PUBLIC_API_BASE:-/api/kairo}
KAIRO_STORE_DIR=${KAIRO_STORE_DIR:-.data/kairo}
MANDELBROT_BOT_ONESHOT=${MANDELBROT_BOT_ONESHOT:-0}
DATABASE_URL=${DATABASE_URL}
