# =============================================================================
# Vultr resources. We provision a small set of compute instances used as
# fallback GPU/CPU capacity for the agent swarm. SSH key is also pulled from
# Vault (id only; the public key is uploaded out of band).
# =============================================================================

resource "vultr_instance" "agent_node" {
  count = var.enabled_clouds.vultr ? 1 : 0

  region   = try(local.vultr_secret.default_region, "ewr")
  plan     = try(local.vultr_secret.default_plan, "vc2-2c-4gb")
  os_id    = 1743 # Ubuntu 22.04 x64
  hostname = "yieldswarm-vultr-${var.environment}-${count.index}"
  label    = "yieldswarm-${var.environment}"
  tags     = [for k, v in local.common_tags : "${k}=${v}"]

  enable_ipv6      = true
  ddos_protection  = true
  activation_email = false
  backups          = "enabled"

  backups_schedule {
    type = "daily"
  }

  ssh_key_ids = compact([try(local.vultr_secret.ssh_key_id, "")])

  # The user_data script will install the Vault Agent + the Akash CLI; the
  # actual heredoc is generated by templatefile() to keep secrets out of state.
  user_data = base64encode(templatefile("${path.module}/templates/cloud-init-agent.sh.tftpl", {
    vault_addr = var.vault_address
    role_id    = var.vault_role_id
  }))
}
