#!/usr/bin/env bash
# Wire Azure SSH public key into subscription + optional VM/VMSS.
#
# Loads key from (first match):
#   AZURE_SSH_PUBLIC_KEY | DEPLOY_SSH_PUBLIC_KEY | AZURE_SSH_PUBLIC_KEY_FILE | ~/.ssh/id_ed25519.pub
# Vault: yieldswarm/providers/azure → ssh_public_key
#
# Usage:
#   ./scripts/azure/wire-ssh-key.sh
#   ./scripts/azure/wire-ssh-key.sh --dry-run
#   AZURE_SSH_PUBLIC_KEY="$(cat ~/.ssh/id_ed25519.pub)" ./scripts/azure/wire-ssh-key.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

RG="${AZURE_RESOURCE_GROUP:-yieldswarm-rg}"
LOCATION="${AZURE_LOCATION:-eastus}"
SUB="${AZURE_SUBSCRIPTION_ID:-}"
ADMIN_USER="${AZURE_ADMIN_USERNAME:-azureuser}"
KEY_NAME="${AZURE_SSH_KEY_NAME:-yieldswarm-deploy-key}"
VM_NAME="${AZURE_VM_NAME:-}"
VMSS_NAME="${AZURE_VMSS_NAME:-}"
OUT_ENV="${ROOT}/.run/azure-ssh.env"

log() { printf '[azure-ssh] %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

# shellcheck disable=SC1091
[[ -f "${ROOT}/scripts/lib/vault-env.sh" ]] && source "${ROOT}/scripts/lib/vault-env.sh" 2>/dev/null || true
[[ -f deploy/config.env ]] && set -a && source deploy/config.env && set +a
[[ -f .env ]] && set -a && source .env && set +a

load_vault_ssh() {
  command -v vault >/dev/null 2>&1 || return 0
  [[ -n "${VAULT_TOKEN:-}" ]] || return 0
  export VAULT_ADDR="${VAULT_ADDR:-https://vault.yieldswarm.io:8200}"
  if vault kv get -format=json yieldswarm/providers/azure >/dev/null 2>&1; then
    [[ -z "${AZURE_SSH_PUBLIC_KEY:-}" ]] && \
      AZURE_SSH_PUBLIC_KEY="$(vault kv get -field=ssh_public_key yieldswarm/providers/azure 2>/dev/null || true)"
    [[ -z "${AZURE_ADMIN_USERNAME:-}" || "${AZURE_ADMIN_USERNAME}" == "azureuser" ]] && \
      AZURE_ADMIN_USERNAME="$(vault kv get -field=admin_username yieldswarm/providers/azure 2>/dev/null || echo azureuser)"
    [[ -z "${AZURE_SUBSCRIPTION_ID:-}" ]] && \
      AZURE_SUBSCRIPTION_ID="$(vault kv get -field=subscription_id yieldswarm/providers/azure 2>/dev/null || true)"
  fi
}

resolve_public_key() {
  if [[ -n "${AZURE_SSH_PUBLIC_KEY:-}" ]]; then
    printf '%s' "$AZURE_SSH_PUBLIC_KEY"
    return
  fi
  if [[ -n "${DEPLOY_SSH_PUBLIC_KEY:-}" ]]; then
    printf '%s' "$DEPLOY_SSH_PUBLIC_KEY"
    return
  fi
  local f="${AZURE_SSH_PUBLIC_KEY_FILE:-}"
  if [[ -n "$f" && -r "$f" ]]; then
    tr -d '\n' < "$f"
    return
  fi
  for candidate in "${HOME}/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_rsa.pub"; do
    if [[ -r "$candidate" ]]; then
      tr -d '\n' < "$candidate"
      return
    fi
  done
  die "No SSH public key found. Set AZURE_SSH_PUBLIC_KEY or generate: ssh-keygen -t ed25519 -C yieldswarm-azure"
}

load_vault_ssh
PUB_KEY="$(resolve_public_key)"
ADMIN_USER="${AZURE_ADMIN_USERNAME:-azureuser}"
SUB="${AZURE_SUBSCRIPTION_ID:-}"

log "Admin user: ${ADMIN_USER}"
log "Key name:   ${KEY_NAME}"
log "Public key: ${PUB_KEY:0:40}…"

mkdir -p "${ROOT}/.run"

if [[ "$DRY_RUN" == "1" ]]; then
  log "[dry-run] would register SSH key in Azure subscription ${SUB:-<current>}"
  log "[dry-run] would write ${OUT_ENV}"
  exit 0
fi

command -v az >/dev/null 2>&1 || die "Azure CLI (az) not installed — apt install azure-cli or brew install azure-cli"

if [[ -n "$SUB" ]]; then
  az account set --subscription "$SUB"
fi

SUB="${SUB:-$(az account show --query id -o tsv)}"
log "Subscription: ${SUB}"

# Register SSH public key at subscription scope (Azure SSH Key resource)
if az sshkey show --name "$KEY_NAME" --resource-group "$RG" >/dev/null 2>&1; then
  log "Updating existing sshkey ${KEY_NAME} in ${RG}"
  az sshkey update --name "$KEY_NAME" --resource-group "$RG" --public-key "$PUB_KEY" -o none
else
  log "Creating sshkey ${KEY_NAME} in ${RG}"
  az group create --name "$RG" --location "$LOCATION" -o none 2>/dev/null || true
  az sshkey create --name "$KEY_NAME" --resource-group "$RG" --public-key "$PUB_KEY" -o none
fi

# Optional: patch existing VM admin key
if [[ -n "$VM_NAME" ]]; then
  log "Updating VM ${VM_NAME} ssh key for user ${ADMIN_USER}"
  az vm user update -g "$RG" -n "$VM_NAME" -u "$ADMIN_USER" --ssh-key-value "$PUB_KEY" -o none 2>/dev/null \
    || log "WARN: VM user update failed (VM may not exist yet)"
fi

# Optional: VMSS model update hint
if [[ -n "$VMSS_NAME" ]]; then
  log "VMSS ${VMSS_NAME}: ensure terraform/azure uses AZURE_SSH_PUBLIC_KEY on next apply"
fi

# Resolve VM public IP if VM exists
AZURE_VM_HOST=""
if [[ -n "$VM_NAME" ]]; then
  AZURE_VM_HOST="$(az vm show -d -g "$RG" -n "$VM_NAME" --query publicIps -o tsv 2>/dev/null || true)"
fi

cat > "$OUT_ENV" <<EOF
# Generated by scripts/azure/wire-ssh-key.sh — do not commit
export AZURE_SSH_PUBLIC_KEY='${PUB_KEY}'
export AZURE_ADMIN_USERNAME='${ADMIN_USER}'
export AZURE_SSH_KEY_NAME='${KEY_NAME}'
export AZURE_RESOURCE_GROUP='${RG}'
export AZURE_SUBSCRIPTION_ID='${SUB}'
export AZURE_VM_NAME='${VM_NAME}'
export AZURE_VM_HOST='${AZURE_VM_HOST}'
# Connect:
#   ssh \${AZURE_ADMIN_USERNAME}@\${AZURE_VM_HOST:-YOUR_AZURE_VM_PUBLIC_IP}
EOF

log "Wrote ${OUT_ENV}"
if [[ -n "$AZURE_VM_HOST" ]]; then
  log "SSH: ssh ${ADMIN_USER}@${AZURE_VM_HOST}"
else
  log "SSH: ssh ${ADMIN_USER}@<VM_PUBLIC_IP>  (set AZURE_VM_NAME to auto-resolve)"
fi

# Seed hint for Vault
log "Persist to Vault:"
log "  vault kv patch yieldswarm/providers/azure ssh_public_key=@- admin_username=${ADMIN_USER} <<< '${PUB_KEY}'"
