#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import sys
from typing import Any


ENV_VAR_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]*$")


def normalize_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, (int, float, str)):
        return str(value)
    return json.dumps(value, separators=(",", ":"), sort_keys=True)


def read_secret_payload(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)

    secret_data = payload.get("data", {}).get("data")
    if not isinstance(secret_data, dict):
        raise ValueError(f"{path} does not look like vault kv get -format=json output")

    return secret_data


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render a shell-safe environment file from Vault KV JSON payloads."
    )
    parser.add_argument("--output", required=True, help="Destination env file.")
    parser.add_argument("secret_files", nargs="+", help="Vault JSON files to merge.")
    args = parser.parse_args()

    merged: dict[str, str] = {}
    sources: dict[str, str] = {}

    for secret_file in args.secret_files:
        secret_data = read_secret_payload(secret_file)
        for key, value in secret_data.items():
            if not ENV_VAR_PATTERN.fullmatch(key):
                raise ValueError(
                    f"{secret_file} contains invalid env var name {key!r}; use uppercase A-Z, 0-9, and underscores only"
                )

            normalized = normalize_value(value)
            if key in merged and merged[key] != normalized:
                previous_source = sources[key]
                raise ValueError(
                    f"Refusing to shadow {key}: defined differently in {previous_source} and {secret_file}"
                )

            merged[key] = normalized
            sources[key] = secret_file

    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write("# Generated by render_vault_env.py. Do not edit.\n")
        for key in sorted(merged):
            handle.write(f"export {key}={shlex.quote(merged[key])}\n")

    os.chmod(args.output, 0o600)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # pragma: no cover - fail closed in bootstrap tooling
        print(str(exc), file=sys.stderr)
        raise SystemExit(1) from exc
